---
- hosts : all
  remote_user : root
  connection: local
  become : yes
  tasks:
    - name: installing dnf
      apt:
        name: dnf
        state: present
      
    - name: restting php using dnf
      shell: dnf module reset php
      
    - name: php enable using dnf
      shell: dnf module enable php:7.4
      
    - name: install required packages using dnf
      shell: dnf install httpd php php-mysqlnd php-gd php-xml mariadb-server mariadb php-mbstring php-json mod_ssl php-intl php-apcu
      
    - name: Start and enable Apache (httpd) service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Start and enable MariaDB (MySQL) service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure the MariaDB installation
      command: mysql_secure_installation < /root/mysql_secure_installation_input.txt
      args:
        creates: /root/mysql_secure_installation_input.txt

    - name: Download MediaWiki
      get_url:
        url: "https://releases.wikimedia.org/mediawiki/{{ mediawiki_version }}/mediawiki-{{ mediawiki_version }}.tar.gz"
        dest: /tmp/mediawiki.tar.gz
        mode: 0644
      vars:
        mediawiki_version: "1.37.1"  # Replace with the desired MediaWiki version

    - name: Extract MediaWiki archive
      unarchive:
        src: /tmp/mediawiki.tar.gz
        dest: /var/www/html/
        remote_src: yes
        owner: apache
        group: apache
        mode: 0755

    - name: Create MediaWiki configuration directory
      file:
        path: /var/www/html/mediawiki/config
        state: directory
        owner: apache
        group: apache
        mode: 0755

    - name: Clean up temporary files
      file:
        path: /tmp/mediawiki.tar.gz
        state: absent

    - name: Set SELinux to allow httpd to connect to the network (if SELinux is enabled)
      selinux:
        policy: targeted
        state: permissive
        type: httpd_t
