name: 'Terraform'
# on:
#   push:
#     branches:
#       - main

  
  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, tag, and push image to Amazon ECRs
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          APP_REPOSITORY: snipe
          IMAGE_TAG: latest
        run: |
          echo $IMAGE_TAG
          echo $APP_REPOSITORY

           docker build -f Dockerfile -t $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG  
           echo "::set-output name=image::$ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.2
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: Terraform Init
      #   id: init 
      #   run: |
      #       cd terraform_with_ALB
      #       terraform init
          
      # - name: Terraform Validate
      #   id: validate
      #   run: |
      #       cd terraform_with_ALB            
      #       terraform validate -no-color
              
      # - name: Terraform Plan
      #   id: plan
      #   run: |
      #       cd terraform_with_ALB        
      #       terraform plan -no-color -input=false 
        # continue-on-error: true
      - name: Terraform destroy
        run: terraform destroy -auto-approve -input=false 
        
      # - name: Terraform Apply
      #   run: | 
      #       cd terraform_with_ALB        
      #       terraform apply -auto-approve -input=false 

